### ISSUE TITLE
y_axis bounds do not change with temperature units.

### ISSUE THREAD

**Issue by trinaldi** [olivesdad/sys-mon#3]
As mentioned in #2 :

There is an issue with the y_axis bounds when dealing with F temps (they don't change).:
![C temps](https://i.imgur.com/9qU6TDP.png)  
![!F temps](https://i.imgur.com/TgyHoOo.png)

I believe it makes sense to change the bounds accordingly.

**Comment by olivesdad** [comment]
Added a vector to use for F. Still need to rescale Y axis to something more realistic for measurements in Fahrenheit

**Comment by trinaldi** [comment]
I can get the `y_axis` to change but the temps are all wrong in the graph..

What I tried to do was create two `Graph` with different `dataset`s. The rationale is, pressing `TAB` check the `unit` and return the chart using `match`.. The Celsius chart returns some odd dots (while the temp is ~60ºC, the line is at ~40ºC). When I press ` TAB` again, the `y_axis` labels do change, but there's no data, just the temp above.
